### ISSUE TITLE
does only redraw on mouse and key events - but not while idling

### ISSUE THREAD

**Issue by jwaldmann** [ivanperez-keera/SpaceInvaders#26] opened 2017-11-08 11:32 UTC
When I run the game, the display only gets updated when something happens (mouse moved or pressed, key pressed). I expect that updates (redraw of moving bullets) should also happen while there is no input event.

(SpaceInvaders-0.4.5 (current master from git), X11-1.8, Yampa-0.10.6.2, HGL-3.2.3.1, ghc-8.2.1, fedora 26)

**Comment by g-pechorin** [comment] 2018-09-05 08:38
Was this fixed? I seem to be having the same problems

**Comment by ivanperez-keera** [comment] 2018-09-06 02:45
I cannot reproduce this: it runs fine on my machine (Ubuntu, ghc 7.10, but the GHC version should not matter).

You may want to take a  look at: https://github.com/ivanperez-keera/SpaceInvaders/blob/develop/src/Animate.hs#L118-L216, and see  in which operation you are getting blocked, and if you are getting any events at all. "Following" the execution by inserting `putStrLn` in different places might help you locate where the program is stuck.

**Comment by chriz-keera** [comment] 2018-10-16 16:07
@jwaldmann and @g-pechorin do you use macOS? I wonder whether there is a connection to this issue: https://github.com/ivanperez-keera/haskanoid/issues/71 (former: https://github.com/ivanperez-keera/haskanoid/issues/68)

**Comment by g-pechorin** [comment] 2018-10-16 16:44
Checking it is on my "TODO" list, but, passing my annual review is at the head :)

**Comment by ivanperez-keera** [comment] 2021-10-03 19:57
@g-pechorin I think #33  was a duplicate of this bug and it's now solved. Please check.

**Comment by ivanperez-keera** [comment] 2021-10-04 18:17
I'm fairly confident that that was the reason, so I'm going to go ahead and close this issue. If the problem persists, please re-open it.

**Closed by ivanperez-keera** 2021-10-04 18:17 UTC
Labels: bug
